# Generated by Django 3.0.6 on 2020-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='employee name')),
                ('position', models.CharField(max_length=150, verbose_name='employee position')),
                ('description', models.TextField(verbose_name='extra information')),
            ],
        ),
    ]
