# Generated by Django 3.0.7 on 2020-06-20 09:47

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_employee_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pages.models.upload_to,
                verbose_name="employee photo",
            ),
        ),
    ]
